### ISSUE TITLE
Adding different game modes

### ISSUE THREAD

**Issue by SharSoft** [ucsb-cs56-projects/cs56-games-connectfour#28] opened 2015-03-13 00:52 UTC
You can add the option of playing different versions of the game on the same board such as Pop Out etc. Refer to link for multiple version game is played (http://en.wikipedia.org/wiki/Connect_Four).

Estimated ~ 400 points

**Comment by jrcryan** [comment] 2015-03-13 01:16
approved
~300 points

**Comment by SElegans** [comment] 2016-09-30 00:32
F16 OK (400 pts)

**Comment by scottpchow23** [comment] 2018-01-24 05:53
This seems like a duplicate of Connect 5.

**Closed by scottpchow23** 2018-01-24 05:53 UTC
