### ISSUE TITLE
Improve Normal and Advanced AI

### ISSUE THREAD

**Issue by brianslee** [ucsb-cs56-projects/cs56-games-connectfour#71] opened 2016-11-23 06:38 UTC
a) Improve the Normal AI to the level at where the Advanced AI is now.
b) Improve the Advanced AI to provide a greater challenge to the human player

Estimate:
a) alone: 100 pts.
b) along: 250 ~ 300 pts
Together: 350~400 pts

**Comment by SElegans** [comment] 2016-11-23 21:36
F16 OK (400 pts)

**Comment by scottpchow23** [comment] 2018-01-24 05:43
This feels like a duplicate of Impossible AI.

**Closed by scottpchow23** 2018-01-24 05:43 UTC
